# Generated by Django 5.0.7 on 2024-09-14 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studyexperience',
            name='school_link',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
